<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{eedc87b0-498f-42a3-9add-b62d0d4a527c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
END_VAR

VAR_INPUT
	qxABBonlineLamp : BOOL;
	qxABBExecutLamp : BOOL;
	qxABBErrorLamp : BOOL;
	qxPauseLamp : BOOL;
	qxEmergySTLamp : BOOL;
	ixPauseButt : BOOL;
	ixResetABB : BOOL;
	qxAutoMode : BOOL;
	qxManualMode : BOOL;
	ixAutoLamp : BOOL;
	ixManualLamp : BOOL;
	qxDoneContainerScan : BOOL;
	qxDoneBuffer1Scan : BOOL;
	qsContainer : STRING;
	qsTask : STRING;
	qsSubTask : STRING;
	mxPlateAvailable : BOOL;
	mxCylinderAvailable : BOOL;
	mxOctagonAvailable : BOOL;
	mwBufferID : INT;
	ixEmptyBuffer : BOOL;
	mwPartID : INT;
	sPartID : ARRAY [1..3] OF STRING:= ['Part 1', 'Part 2', 'Part 3'];
END_VAR

VAR_OUTPUT
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AutomationLibrary();
Visualaisation_Control();
RobotPosTracker();
ABB_Control_FB();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="60" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>